name: CreateRelease

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  CreateRelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
          ssh-key: ${{ secrets.BOWLERBOT_SSH_KEY }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOWLERBOT_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.generate-changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ startsWith(github.ref, 'refs/tags/0') }}
