name: PRConsumers

on:
  release:
    types: [published]

jobs:
  PRConsumers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.BOWLERBOT_PAT }}
          script: |
            github.repos.createDispatchEvent({
              owner: "CommonWealthRobotics",
              repo: "bowler-proto-kotlin",
              event_type: "bowler-proto-release",
              client_payload: { release: process.env.GITHUB_SHA }
            });
