name: TagNewVersion

on:
  push:
    branches:
      - master
    paths:
      - "version.properties"

jobs:
  TagNewVersion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
          ssh-key: ${{ secrets.BOWLERBOT_SSH_KEY }}

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.BOWLERBOT_GPG_KEY }}
          passphrase: ${{ secrets.BOWLERBOT_GPG_KEY_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Parse this tag
        id: parse-tag
        run: |
          THIS_TAG=$(grep 'projectVersion' 'version.properties' | awk '{ split($0,a,"="); print a[2] }')
          echo "::set-output name=tag::$(echo $THIS_TAG)"

      - name: Continue if there is a new version
        run: |
          ! git rev-parse $THIS_TAG >/dev/null 2>&1
        env:
          THIS_TAG: ${{ steps.parse-tag.outputs.tag }}

      - name: Tag new version
        run: git tag -s -m "$THIS_TAG" $THIS_TAG
        env:
          THIS_TAG: ${{ steps.parse-tag.outputs.tag }}

      - name: Push new tag
        run: git push --tags
